#!/bin/bash
test_single()
{
    #all=(30 40 45 50 55 60)
    all=(50 50)
    type=$1
    if [ "${type}" == "" ];then
        type="capture"
    fi
    for i in ${all[*]} 
    do
        cur=`date +%Y%m%d_%H%M%S`
        testname="DNSmbp${i}_${cur}_${type}"
        echo `bash start_test_${type} ${testname} ${i}`
        echo "sleep 5min wait next test for io******************"
        sleep 30
        echo "******************"
    done
}

test_complex()
{
    #http_mbp,dns_mbp
    #all=(5,5 1,2 3,4)
    all=(1,1)
    echo -e "\n[test_complex]${all}***********************************\n"
    type=$1
    if [ "${type}" == "" ];then
        type="capture"
    fi
    for i in ${all[*]} 
    do
        h=`echo ${i}|sed 's/,.*//g'`
        d=`echo ${i}|sed 's/.*,//g'`
        cur=`date +%Y%m%d_%H%M%S`
        testname="COMmbpHTTP${h}_DNS${d}_${cur}_${type}"
        echo `bash TCForHD_${type} ${testname} ${h} ${d}`
        echo -e "\nsleep 5min wait next test for io******************\n"
        sleep 30
        echo -e "\n******************"
    done
}

#test_single
test_complex
