#!/bin/bash
echo "save_dir:$1; 控制参数:--mbps:$2"

if [[ $1 == "" ]];then
    echo "dir is null[$1]"
    exit 1
fi
testname=$1
if [[ $2 == "" ]];then
    echo "控制参数 为空[$2]"
    exit 1
fi
carg=$2
mkdir $testname
sshpass -p threatbook ssh root@192.168.100.121 'echo "">/tmp/test_tip.out' 
echo "************check test_tip.out"
sshpass -p threatbook ssh root@192.168.100.121 'cat /tmp/test_tip.out|wc -l' 

curl http://192.168.100.121:8089/status >t_${testname}.log
echo "****************************" >>t_${testname}.log
time tcpreplay --mbps=${carg} -i ens224 -l 500 dns_20327.pcap >>t_${testname}.log
echo "****************************" >>t_${testname}.log
curl http://192.168.100.121:8089/status >>t_${testname}.log

sshpass -p threatbook scp root@192.168.100.121:/tmp/test_tip.out ${testname}/
mv t_${testname}.log ${testname}/
