#!/bin/bash

echo "save_dir:$1; 控制参数:--mbps:$2"

if [[ $1 == "" ]];then
    echo "dir is null[$1]"
    exit 1
fi
testname=$1
if [[ $2 == "" ]];then
    echo "控制参数 为空[$2]"
    exit 1
fi
carg=$2
mkdir $testname
outfile="test_tip.out"
#cp out到文件服务器
#sshpass -p threatbook scp -r test_file root@192.168.100.121:~

sshpass -p threatbook ssh root@192.168.100.121 "echo ''>/tmp/${outfile}"
echo "************check test_tip.out"
sshpass -p threatbook ssh root@192.168.100.121 "cat /tmp/${outfile}|wc -l" 

curl http://192.168.100.121:8089/status >t_${testname}.log
echo "****************************" >>t_${testname}.log
if [[ $3 == "HTTP" ]];then
    time tcpreplay-edit --unique-ip  -M ${carg} -i ens224 -l 50 http/http5000_cnblogs.pcap >>t_${testname}.log
fi
if [[ $3 == "DNS" ]];then
    time tcpreplay-edit --unique-ip  -M ${carg}  -i ens224 -l 100 dns_20327.pcap >>t_${testname}.log
fi
echo "****************************" >>t_${testname}.log
sleep 10 #防止io排队问题，次为止next修改为从second_process_count持续5s为0后再次统计
curl http://192.168.100.121:8089/status >>t_${testname}.log
sleep 2

mv t_${testname}.log ${testname}/
mv ${testname} /fileserver/

#save out
#sshpass -p threatbook scp root@192.168.100.121:/tmp/test_tip.out ${testname}/
#sshpass -p threatbook ssh root@192.168.100.121 "bash ~/test_file ${outfile} ${testname}"
