#!/bin/bash
source sshuse  #use for sshdoing


tc_use()
{
    #local try_time=3            #延时倍数，此位置为sleep的使用基线
    local try_time=3            #延时倍数，此位置为sleep的使用基线
    local continue_time=$((48 * try_time))  #当前pcap包,1mbps/-line=1 使用48s
    local http_carg=$1
    local dns_carg=$2
    local log_file=$3
    local hnum=$((http_carg * try_time))
    local dnum=$((dns_carg * 3 * try_time))
    echo "*****http_carg:${http_carg};dns:${dns_carg};http_num[${hnum}];dns_num[${dnum}]"
    time tcpreplay --mbps=${http_carg} -i em2 -l ${hnum} http5000_cnblogs.pcap>${log_file}_http&
    time tcpreplay --mbps=${dns_carg} -i em2 -l ${dnum} dns_20327.pcap>${log_file}_dns&
    local use_time=$((continue_time + 10))
    echo `sleep ${use_time}`
}

test_tc_use()
{
    tc_use 30 20 test
    tc_use 10 10 test
    tc_use 1 12  test
    tc_use 30 2  test
}

start_test()
{
    if [[ $1 == "" ]];then
        echo "dir is null[$1]"
        exit 1
    fi
    testname=$1
    http_c=$2
    dns_c=$3
    setup
    curl http://192.168.100.171:8089/status>t_${testname}.log

    tc_use $http_c $dns_c t_${testname}.log
    curl http://192.168.100.171:8089/status>>t_${testname}.log

    teardown ${testname}

}

setup()    # init use for testcase
{
    fileph="/tmp/test_tip.out"
    ssh_doing "echo ''>${fileph}"
    ssh_doing "cat ${fileph}|wc -l"
}

teardown()  #end process for testcase
{
    save_dir=$1
    defdir="/tmp/test/${save_dir}"    
    fileph="/tmp/test_tip.out"
    ssh_doing "mkdir ${defdir}|cp ${fileph} ${defdir}"
    ssh_doing "echo ''>${fileph}"
    ssh_doing "cat ${fileph}|wc -l"

    
    mkdir ${save_dir}
    mv t_${save_dir}.log ${save_dir}/
    mv t_${save_dir}.log_dns ${save_dir}/
    mv t_${save_dir}.log_http ${save_dir}/
    mv ${save_dir} /fileserver/
    #ssh_doing "mv ${defdir} /filesever/"
}

#start_test a 1 1
start_test $1 $2 $3

