#!/bin/bash
check_file_c(){
    a=`stat -c %Y /tmp/$1`  #获取文件的修改时间（秒为单位）
    b=`date +%s`       #获取当前系统的时间 (秒为单位）
    
    echo "[$a;$b]"
    if [ $[ $b - $a ] -gt 5 ];   #判断当前时间和文件修改时间差（5秒）
    then
        cp /tmp/$1 /fileserver/$2
    else
        ech "sleep 10 ********"
        sleep 10
        check_file_c $1 $2
    fi
}
check_file_c $1 $2
